from flask import Flask, jsonify, request
import os

app = Flask(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# YOUR DATA
# ─────────────────────────────────────────────────────────────────────────────

LICENSES = {
    "SD-ULTRA-TEST-0001": {"expires": "2027-12-31", "plan": "ultra"},
}

COOKIES_NETSCAPE = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_labs.google	FALSE	/	TRUE	1780705083	__Secure-next-auth.pkce.code_verifier	eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..8rNQg50E4lVpKih7.O_rMGV8ywqj9FQTdc_tHKjgVf6dGu6Ei2_fDJW9dc6mvahOWJ1LOu_EWp4jN7X3Xus0N-yEA-AhW42b4xi2_PS3RQF1Bun6HhnboxdgUlmx-iE2xpMibF8GUFDgjDBOTpS5ybmwuIZpLxhJetGKUfq5xVqgUW1zjleBLDU93XIZuGuZ_znU.5AN2szZLOfYQ6GiaiMw8Ww
labs.google	FALSE	/	FALSE	1783295421	EMAIL	%22rafixspark%40gmail.com%22
#HttpOnly_labs.google	FALSE	/	TRUE	1780801364	__Host-next-auth.csrf-token	aa6e511cba57faf001ee2ff2ed431acb742d34f7cfe1a896f67d1bc8102260ff%7C72143fc15bbe298f51ed759063cfb09884c4c8f389e075bc91f9b276aad7bbb5
#HttpOnly_labs.google	FALSE	/	TRUE	1780801364	__Secure-next-auth.callback-url	https%3A%2F%2Flabs.google%2Ffx%2Ftools%2Fflow
#HttpOnly_labs.google	FALSE	/	TRUE	1783296181	__Secure-next-auth.session-token	eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..HNqSCWiy_24ihW_n.Hllr-D0myEtQdYiBTzfyY9HBYPC2lYGlAFVTJxEwc6RAhUzIJ5Tl0nCxnbECp0CruaDwDvYmbkRvokDlkGmM3TEv_UX_zEPJN3j3lw9IgUt5vUoCI3rUGf__MKCA7NP0UeQMHjzBvJT3aWTmVX4g6wj7I6nz9yl_YHubObvlqzxLSNaMVULYuKm50KiHt087LM6OFkSLlgt7uf8c_-HX-CXHXaZ36CaQNjqtM8vdMbLZg9iysW7gHoNPiv16_FsYfJMPHj_0pN96292-yikWmlQ2rv09wvuiVZWaOJEL5PJGfg-eU51j5F5Z7dlE5HIc3VOP4Sxs37uTRRucZCGiHVnLqoDq-u2nijzo6zlBhjNZ7CrexQP8gwpZL_mKIUjlHtlKPTqvENHEmQ3Pz4ZYThdhaUa6iIeDBlbzomWI5km2d6qshMEmS_C1Qt4ufaq8GLIyE87i78gBxEMhuhFj9qJf2XPBUC01e_BgRlnBULadiNxN0ox5m2r389kxjpkv-Ls8WEWs1LWTcUEKGwTRdzPnb2hq220SdxCUoX5Phy8FZKLKg4kqBmiVFklFcqHezgro6toyz7JMRhiGsiXlTLkUPINJA4HoAebkvj3O9I-SU37aEJJdaxqA2Pd9L_jyIvalQfUFYi0e3e3qHFAkRVrh-z5ktqp7G1Xjautk78Unx-p_GplXkLK050N0mVZeL4-Ouq1uEyM0ibaF8RtCdH5_MH909lLyikueikBJCn1_Co5KKKs8W4Sjpz60At0MsGt6XIAz0T6oYR5UIbhrtqeBx-5G4U_X-3YbMPX-UQX7NNIvcjc1l2beqD4m9St39mshqy9YVBBfMCp7jckWZKgTr_xj0d3_JhzPdAxB37i1bAtbfFGjCVER6EjsFfYuAcdA8cL-ZAOcFNxWprZ-9VSjuYKvL_J5mwkN3p6u0TN-8j18nf6Z9-hiHdy83bI4uPQYBNkk5MRrBW64-pHhklVO1ZnwzyT7PlZLGBCfcdmsY_BxXEVae2DMmhb77pZU0O97Zb4SmBpI9I54RyB5.2hj8wblIbPjftqZ9Gcst6g
#HttpOnly_labs.google	FALSE	/	TRUE	1780705083	__Secure-next-auth.state	eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..LGHMbcVHw4C83j-L.AAHx12IVzKc_UkHQNDyBC9FCyTRYgXuvJjQGuvGG5tSCBbm9JKGEsLekzlk5Io9ZTivpBkIj6gD4ctI64_er8cKPfINrlh5v-k-U6-ywxde3E41b9ypgFAJLUu5wd-Z-R6MynAajN8W1UPlDloN_LnlNajr7ajwF226hE0k5c8xdOcG6HDU.iGIoqqfDjtpRFtVZ9e661w
.labs.google	TRUE	/	FALSE	1815264149	_ga	GA1.1.35101338.1780703426
.labs.google	TRUE	/	FALSE	1815264151	_ga_X2GNH8R5NS	GS2.1.s1780703426$o1$g1$t1780704151$j11$l0$h1117841660
"""

# ─────────────────────────────────────────────────────────────────────────────

def cors(resp):
    resp.headers['Access-Control-Allow-Origin']  = '*'
    resp.headers['Access-Control-Allow-Methods'] = 'GET, OPTIONS'
    resp.headers['Access-Control-Allow-Headers'] = '*'
    resp.headers['Cache-Control'] = 'no-store'
    return resp

@app.after_request
def add_cors(resp):
    return cors(resp)

@app.route('/sd-flow-data', methods=['GET', 'OPTIONS'])
def flow_data():
    if request.method == 'OPTIONS':
        return cors(app.response_class(status=204))
    return jsonify({
        "licenses": LICENSES,
        "cookies_netscape": COOKIES_NETSCAPE,
    })

@app.route('/', methods=['GET'])
def index():
    return 'SD Flow Server is running.', 200

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 8080))
    app.run(host='0.0.0.0', port=port)
