from flask import Flask, jsonify, request
import os

app = Flask(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# LICENSE KEYS — add/edit/remove here, then push to GitHub
# ─────────────────────────────────────────────────────────────────────────────

LICENSES = {
    "SD-ULTRA-TEST-0001": {"expires": "2025-12-31", "plan": "ultra"},
    # "SD-ULTRA-NAME-0002": {"expires": "2025-09-01", "plan": "ultra"},
    # "SD-BASIC-NAME-0003": {"expires": "2025-07-01", "plan": "basic"},
}

# ─────────────────────────────────────────────────────────────────────────────
# COOKIES — paste your full Cookie-Editor Netscape export between the triple
# quotes below. Replace everything between them when your session expires.
# ─────────────────────────────────────────────────────────────────────────────

COOKIES_NETSCAPE = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
PASTE YOUR COOKIE-EDITOR EXPORT HERE
"""

# ─────────────────────────────────────────────────────────────────────────────


def add_cors(resp):
    resp.headers['Access-Control-Allow-Origin']  = '*'
    resp.headers['Access-Control-Allow-Methods'] = 'GET, OPTIONS'
    resp.headers['Access-Control-Allow-Headers'] = '*'
    resp.headers['Cache-Control'] = 'no-store'
    return resp

@app.after_request
def after_request(resp):
    return add_cors(resp)

@app.route('/sd-flow-data', methods=['GET', 'OPTIONS'])
def flow_data():
    if request.method == 'OPTIONS':
        return add_cors(app.response_class(status=204))
    return jsonify({
        "licenses":        LICENSES,
        "cookies_netscape": COOKIES_NETSCAPE,
    })

@app.route('/', methods=['GET'])
def index():
    return 'SD Flow Server is running.', 200

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 8080))
    app.run(host='0.0.0.0', port=port)
