from flask import Flask, jsonify, request
import os

app = Flask(__name__)

# License database
LICENSES = {
    "1": {"expires": "2027-12-31", "plan": "ultra"},
}

# Your working Netscape string
COOKIES_NETSCAPE = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
labs.google	FALSE	/	FALSE	1783304053	EMAIL	%22rafixspark%40gmail.com%22
#HttpOnly_labs.google	FALSE	/	TRUE	1780798468	__Host-next-auth.csrf-token	ab1c1bcecfe18f017ab6fa6e891376933672bf48541dc0df07fc1afb3764f95e%7C049e8c077e2a32a792380e19990e65f9fca1a7e6f3d587bfb6af7593b3af44d3
#HttpOnly_labs.google	FALSE	/	TRUE	1780798468	__Secure-next-auth.callback-url	https%3A%2F%2Flabs.google
#HttpOnly_labs.google	FALSE	/	TRUE	1783304062	__Secure-next-auth.session-token	eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..PQDJqUZwlWQlEqx_.k-875DCp-8X-g7rnpFeB4ClP71fvH1acWyABw1jxILaN8_ulyeosyFMfk8rI8wSg4k07Xh9Mv321ZzJlP54awp0MWbAwISe4_gs01nsWx3YRQV1wPczo8s3ifqxxusy1kTX-uRebLlVVnCRIm3BsH1lVGKTd8HkbteAbIJv7z8yQ9y_alsSGDjRThMttQybVrmIGtYkTVL2Pbd9xYx3M12cEnDoCVTxMAOqNxM7cfKD3iJU7jRe_bqR6P5yrGwD3fP9ZYDTvg_n506s0503OqJfCqhF7ViBTscKi4Z9ku-xCUKUe4_M9NZegPoqJ39n8iPm5yWNl1JDfNe4oRQJcibji40V2TzBm3pfgj4nAk1H28Z6lbOTIUFFJ9gRsuEObYBTzKc-SxotPhk012pRfGnM0LXm0ihy1hCjmKNdrrOIJ42wC043LJiwCRE_CpJypUwcBuf-IFmhNTmlhwwv70Wo0vFqR9zwOEdQYGfSY1AC7Gle9_2RQt60DfCJfSWgu8Yku5bv3c11Ongip-yMsp-L2VxSA6jWaWN947YjIrhKQ-EkHCkhJkOfPRGRmqeyJY6UHkxHmqDvxuAyJF4lWd5Fb_RbyzLaFTA3EGUkUUy4jj7qlB2jHhKVA-XzpKsL9bcvDvEv8L6xtvCIcT_dP34VIQRKOo7nMZet5fBORRVieeqQcnGw6PSyNAKBcKVqfGlWX-qwWsL_YW2RF2KrQuNPsHWHxFbL_pewrmDOu7KW2htDPy25TWeKxwnbtouySsI60rLJi5LoE8kWlWBbvbprvW_DDRXZvFn9qCHoB1equ6wqk4t1tB8fZ0nc_yE_QJCtU_wux4j7kXRDRXaWiQGk7JKUu4V7ibRjIR8OAqtR_uJ3BBBlbYRqTpSAwhdqM3O2LuaqqKBarg6siEvYldYFYfsG9_0KU3KRmPJZyLarHL3f_SqtIaofPe7mTw1eb7cLbqNIm9FWbUjv3x8lzYP0hu-xmoQ.7BXermmsKT5aNw5mLoI50A
.labs.google	TRUE	/	FALSE	1815272053	_ga	GA1.1.811632635.1780712054
.labs.google	TRUE	/	FALSE	1815272054	_ga_X2GNH8R5NS	GS2.1.s1780712053$o1$g0$t1780712053$j60$l0$h1553435741
"""

def cors_response(data):
    resp = jsonify(data)
    resp.headers['Access-Control-Allow-Origin'] = '*'
    resp.headers['Access-Control-Allow-Methods'] = 'GET, OPTIONS'
    resp.headers['Access-Control-Allow-Headers'] = '*'
    return resp

@app.route('/sd-flow-data', methods=['GET', 'OPTIONS'])
def flow_data():
    if request.method == 'OPTIONS':
        return cors_response({})
    return cors_response({
        "licenses": LICENSES,
        "cookies_netscape": COOKIES_NETSCAPE.strip(),
    })

if __name__ == '__main__':
    # Use Railway's port or default to 8080
    port = int(os.environ.get('PORT', 8080))
    app.run(host='0.0.0.0', port=port)
